server:
  address: 127.0.0.1
  port: 9099

spring:
  application:
    name: ragent-mcp-server

ragent:
  bit:
    datasource:
      url: jdbc:postgresql://192.168.137.100:5432/ragent_bit?client_encoding=UTF8
      username: postgres
      password: postgres
    pending-order:
      timeout: 5m
      scan-interval: 1m
